#!/bin/bash          

#Off by +5 hours

if dtest time --gt '11:00:00' && dtest time --le '16:00:00'; then 
	wal -i /home/jacob/Pictures/wallpapers/morning -o wal-set
	echo "morn"
elif dtest time --gt '16:00:00' && dtest time --le '22:00:00'; then 
	wal -i /home/jacob/Pictures/wallpapers/day -o wal-set
	echo "day"
elif dtest time --gt '22:00:00' || dtest time --le '11:00:00'; then 
	wal -i /home/jacob/Pictures/wallpapers/night -o wal-set
	echo "night"
else
	wal -i /home/jacob/Pictures/wallpapers/all -o wal-set 
fi	
